### ISSUE TITLE
Be smarter about saving history

### ISSUE THREAD

**Issue by bandali** [lujun9972/el-dmenu#8]
As of now, even my incomplete command names are added to the history.  For instance, to launch `thunar` I often just type `thun`, and I’ve noticed that this package retains `thun` as a separate entry, which isn’t an actual executable name.

On the one hand, I like that my custom commands such as `thunar -v` get added to the history, but it would be nice if incomplete version of commands were discarded and not recorded.

**Comment by cryptorick** [comment]
Sorry, the above commit https://github.com/lujun9972/el-dmenu/commit/1e7cf4546c7585b1730c652689365fc3bd9f7f35 (now unreachable (by branch)) was for issue #7, not this issue.  (I redid a fix for #7 under a different commit.)  The fix for *this* commit is https://github.com/lujun9972/el-dmenu/commit/a4d4784ce76fcb89527b5365dc4f0c76c9f34ba0.

**Comment by cryptorick** [comment]
Sorry about that @bandali0 and @lujun9972; apparently two is one too many issues for me to handle at one time. lolol :)

**Comment by cryptorick** [comment]
@bandali0 please close the issue once you are satisfied with the new commits (which @lujun9972 just put on master). Thanks!
